// Code generated by mockery. DO NOT EDIT.

package jfmock

import (
	mock "github.com/stretchr/testify/mock"
	models "jf.go.techchallenge/internal/models"

	repository "jf.go.techchallenge/internal/repository"
)

// Person is an autogenerated mock type for the Person type
type Person struct {
	mock.Mock
}

type Person_Expecter struct {
	mock *mock.Mock
}

func (_m *Person) EXPECT() *Person_Expecter {
	return &Person_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: person
func (_m *Person) Delete(person *models.Person) error {
	ret := _m.Called(person)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Person) error); ok {
		r0 = rf(person)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Person_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Person_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - person *models.Person
func (_e *Person_Expecter) Delete(person interface{}) *Person_Delete_Call {
	return &Person_Delete_Call{Call: _e.mock.On("Delete", person)}
}

func (_c *Person_Delete_Call) Run(run func(person *models.Person)) *Person_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Person))
	})
	return _c
}

func (_c *Person_Delete_Call) Return(_a0 error) *Person_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Person_Delete_Call) RunAndReturn(run func(*models.Person) error) *Person_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: filters
func (_m *Person) FindAll(filters repository.Filters) ([]models.Person, error) {
	ret := _m.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(repository.Filters) ([]models.Person, error)); ok {
		return rf(filters)
	}
	if rf, ok := ret.Get(0).(func(repository.Filters) []models.Person); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(repository.Filters) error); ok {
		r1 = rf(filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Person_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type Person_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - filters repository.Filters
func (_e *Person_Expecter) FindAll(filters interface{}) *Person_FindAll_Call {
	return &Person_FindAll_Call{Call: _e.mock.On("FindAll", filters)}
}

func (_c *Person_FindAll_Call) Run(run func(filters repository.Filters)) *Person_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(repository.Filters))
	})
	return _c
}

func (_c *Person_FindAll_Call) Return(_a0 []models.Person, _a1 error) *Person_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Person_FindAll_Call) RunAndReturn(run func(repository.Filters) ([]models.Person, error)) *Person_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: guid
func (_m *Person) FindOne(guid string) (models.Person, error) {
	ret := _m.Called(guid)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Person, error)); ok {
		return rf(guid)
	}
	if rf, ok := ret.Get(0).(func(string) models.Person); ok {
		r0 = rf(guid)
	} else {
		r0 = ret.Get(0).(models.Person)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(guid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Person_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type Person_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - guid string
func (_e *Person_Expecter) FindOne(guid interface{}) *Person_FindOne_Call {
	return &Person_FindOne_Call{Call: _e.mock.On("FindOne", guid)}
}

func (_c *Person_FindOne_Call) Run(run func(guid string)) *Person_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Person_FindOne_Call) Return(_a0 models.Person, _a1 error) *Person_FindOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Person_FindOne_Call) RunAndReturn(run func(string) (models.Person, error)) *Person_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: person, inputCourses
func (_m *Person) Save(person *models.Person, inputCourses []models.Course) error {
	ret := _m.Called(person, inputCourses)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Person, []models.Course) error); ok {
		r0 = rf(person, inputCourses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Person_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Person_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - person *models.Person
//   - inputCourses []models.Course
func (_e *Person_Expecter) Save(person interface{}, inputCourses interface{}) *Person_Save_Call {
	return &Person_Save_Call{Call: _e.mock.On("Save", person, inputCourses)}
}

func (_c *Person_Save_Call) Run(run func(person *models.Person, inputCourses []models.Course)) *Person_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Person), args[1].([]models.Course))
	})
	return _c
}

func (_c *Person_Save_Call) Return(_a0 error) *Person_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Person_Save_Call) RunAndReturn(run func(*models.Person, []models.Course) error) *Person_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewPerson creates a new instance of Person. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPerson(t interface {
	mock.TestingT
	Cleanup(func())
}) *Person {
	mock := &Person{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
